package com.fm.fmlib.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORY_TITLE.
 */
public class CategoryTitle {

    /** Not-null value. */
    private String id;
    private String name;

    public CategoryTitle() {
    }

    public CategoryTitle(String id, String name) {
        this.id = id;
        this.name = name;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
