package com.fm.fmlib.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORY_LIST.
 */
public class CategoryList {

    /** Not-null value. */
    private String category;
    /** Not-null value. */
    private String category_id;
    /** Not-null value. */
    private String name;

    public CategoryList() {
    }

    public CategoryList(String category, String category_id, String name) {
        this.category = category;
        this.category_id = category_id;
        this.name = name;
    }

    /** Not-null value. */
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String category) {
        this.category = category;
    }

    /** Not-null value. */
    public String getCategory_id() {
        return category_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory_id(String category_id) {
        this.category_id = category_id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

}
