package com.fm.fmlib.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.fm.fmlib.dao.User;
import com.fm.fmlib.dao.Inn;
import com.fm.fmlib.dao.MyProperty;
import com.fm.fmlib.dao.ProductTag;
import com.fm.fmlib.dao.CategoryTitle;
import com.fm.fmlib.dao.CategoryList;
import com.fm.fmlib.dao.LocalTitle;
import com.fm.fmlib.dao.LocalList;
import com.fm.fmlib.dao.ProductBreviary;
import com.fm.fmlib.dao.LaunchProfile;
import com.fm.fmlib.dao.Product;

import com.fm.fmlib.dao.UserDao;
import com.fm.fmlib.dao.InnDao;
import com.fm.fmlib.dao.MyPropertyDao;
import com.fm.fmlib.dao.ProductTagDao;
import com.fm.fmlib.dao.CategoryTitleDao;
import com.fm.fmlib.dao.CategoryListDao;
import com.fm.fmlib.dao.LocalTitleDao;
import com.fm.fmlib.dao.LocalListDao;
import com.fm.fmlib.dao.ProductBreviaryDao;
import com.fm.fmlib.dao.LaunchProfileDao;
import com.fm.fmlib.dao.ProductDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig innDaoConfig;
    private final DaoConfig myPropertyDaoConfig;
    private final DaoConfig productTagDaoConfig;
    private final DaoConfig categoryTitleDaoConfig;
    private final DaoConfig categoryListDaoConfig;
    private final DaoConfig localTitleDaoConfig;
    private final DaoConfig localListDaoConfig;
    private final DaoConfig productBreviaryDaoConfig;
    private final DaoConfig launchProfileDaoConfig;
    private final DaoConfig productDaoConfig;

    private final UserDao userDao;
    private final InnDao innDao;
    private final MyPropertyDao myPropertyDao;
    private final ProductTagDao productTagDao;
    private final CategoryTitleDao categoryTitleDao;
    private final CategoryListDao categoryListDao;
    private final LocalTitleDao localTitleDao;
    private final LocalListDao localListDao;
    private final ProductBreviaryDao productBreviaryDao;
    private final LaunchProfileDao launchProfileDao;
    private final ProductDao productDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        innDaoConfig = daoConfigMap.get(InnDao.class).clone();
        innDaoConfig.initIdentityScope(type);

        myPropertyDaoConfig = daoConfigMap.get(MyPropertyDao.class).clone();
        myPropertyDaoConfig.initIdentityScope(type);

        productTagDaoConfig = daoConfigMap.get(ProductTagDao.class).clone();
        productTagDaoConfig.initIdentityScope(type);

        categoryTitleDaoConfig = daoConfigMap.get(CategoryTitleDao.class).clone();
        categoryTitleDaoConfig.initIdentityScope(type);

        categoryListDaoConfig = daoConfigMap.get(CategoryListDao.class).clone();
        categoryListDaoConfig.initIdentityScope(type);

        localTitleDaoConfig = daoConfigMap.get(LocalTitleDao.class).clone();
        localTitleDaoConfig.initIdentityScope(type);

        localListDaoConfig = daoConfigMap.get(LocalListDao.class).clone();
        localListDaoConfig.initIdentityScope(type);

        productBreviaryDaoConfig = daoConfigMap.get(ProductBreviaryDao.class).clone();
        productBreviaryDaoConfig.initIdentityScope(type);

        launchProfileDaoConfig = daoConfigMap.get(LaunchProfileDao.class).clone();
        launchProfileDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        innDao = new InnDao(innDaoConfig, this);
        myPropertyDao = new MyPropertyDao(myPropertyDaoConfig, this);
        productTagDao = new ProductTagDao(productTagDaoConfig, this);
        categoryTitleDao = new CategoryTitleDao(categoryTitleDaoConfig, this);
        categoryListDao = new CategoryListDao(categoryListDaoConfig, this);
        localTitleDao = new LocalTitleDao(localTitleDaoConfig, this);
        localListDao = new LocalListDao(localListDaoConfig, this);
        productBreviaryDao = new ProductBreviaryDao(productBreviaryDaoConfig, this);
        launchProfileDao = new LaunchProfileDao(launchProfileDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Inn.class, innDao);
        registerDao(MyProperty.class, myPropertyDao);
        registerDao(ProductTag.class, productTagDao);
        registerDao(CategoryTitle.class, categoryTitleDao);
        registerDao(CategoryList.class, categoryListDao);
        registerDao(LocalTitle.class, localTitleDao);
        registerDao(LocalList.class, localListDao);
        registerDao(ProductBreviary.class, productBreviaryDao);
        registerDao(LaunchProfile.class, launchProfileDao);
        registerDao(Product.class, productDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        innDaoConfig.getIdentityScope().clear();
        myPropertyDaoConfig.getIdentityScope().clear();
        productTagDaoConfig.getIdentityScope().clear();
        categoryTitleDaoConfig.getIdentityScope().clear();
        categoryListDaoConfig.getIdentityScope().clear();
        localTitleDaoConfig.getIdentityScope().clear();
        localListDaoConfig.getIdentityScope().clear();
        productBreviaryDaoConfig.getIdentityScope().clear();
        launchProfileDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public InnDao getInnDao() {
        return innDao;
    }

    public MyPropertyDao getMyPropertyDao() {
        return myPropertyDao;
    }

    public ProductTagDao getProductTagDao() {
        return productTagDao;
    }

    public CategoryTitleDao getCategoryTitleDao() {
        return categoryTitleDao;
    }

    public CategoryListDao getCategoryListDao() {
        return categoryListDao;
    }

    public LocalTitleDao getLocalTitleDao() {
        return localTitleDao;
    }

    public LocalListDao getLocalListDao() {
        return localListDao;
    }

    public ProductBreviaryDao getProductBreviaryDao() {
        return productBreviaryDao;
    }

    public LaunchProfileDao getLaunchProfileDao() {
        return launchProfileDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

}
