package com.fm.fmlib.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.fm.fmlib.dao.User;
import com.fm.fmlib.dao.Inn;
import com.fm.fmlib.dao.MyProperty;

import com.fm.fmlib.dao.UserDao;
import com.fm.fmlib.dao.InnDao;
import com.fm.fmlib.dao.MyPropertyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig innDaoConfig;
    private final DaoConfig myPropertyDaoConfig;

    private final UserDao userDao;
    private final InnDao innDao;
    private final MyPropertyDao myPropertyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        innDaoConfig = daoConfigMap.get(InnDao.class).clone();
        innDaoConfig.initIdentityScope(type);

        myPropertyDaoConfig = daoConfigMap.get(MyPropertyDao.class).clone();
        myPropertyDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        innDao = new InnDao(innDaoConfig, this);
        myPropertyDao = new MyPropertyDao(myPropertyDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Inn.class, innDao);
        registerDao(MyProperty.class, myPropertyDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        innDaoConfig.getIdentityScope().clear();
        myPropertyDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public InnDao getInnDao() {
        return innDao;
    }

    public MyPropertyDao getMyPropertyDao() {
        return myPropertyDao;
    }

}
