package com.fm.fmlib.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.fm.fmlib.dao.user;
import com.fm.fmlib.dao.inn;

import com.fm.fmlib.dao.userDao;
import com.fm.fmlib.dao.innDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig innDaoConfig;

    private final userDao userDao;
    private final innDao innDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(userDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        innDaoConfig = daoConfigMap.get(innDao.class).clone();
        innDaoConfig.initIdentityScope(type);

        userDao = new userDao(userDaoConfig, this);
        innDao = new innDao(innDaoConfig, this);

        registerDao(user.class, userDao);
        registerDao(inn.class, innDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        innDaoConfig.getIdentityScope().clear();
    }

    public userDao getUserDao() {
        return userDao;
    }

    public innDao getInnDao() {
        return innDao;
    }

}
