package com.fm.fmlib.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INN.
 */
public class Inn {

    private String innId;
    private String innerContact;
    private String innerHead;
    private String innerIdentify;
    private String innerMoblie;
    private String innerScore;
    private String innerServe;
    private String innerTodayServe;
    private String innHead;
    private String innProducts;
    private String innName;
    private Long id;

    public Inn() {
    }

    public Inn(Long id) {
        this.id = id;
    }

    public Inn(String innId, String innerContact, String innerHead, String innerIdentify, String innerMoblie, String innerScore, String innerServe, String innerTodayServe, String innHead, String innProducts, String innName, Long id) {
        this.innId = innId;
        this.innerContact = innerContact;
        this.innerHead = innerHead;
        this.innerIdentify = innerIdentify;
        this.innerMoblie = innerMoblie;
        this.innerScore = innerScore;
        this.innerServe = innerServe;
        this.innerTodayServe = innerTodayServe;
        this.innHead = innHead;
        this.innProducts = innProducts;
        this.innName = innName;
        this.id = id;
    }

    public String getInnId() {
        return innId;
    }

    public void setInnId(String innId) {
        this.innId = innId;
    }

    public String getInnerContact() {
        return innerContact;
    }

    public void setInnerContact(String innerContact) {
        this.innerContact = innerContact;
    }

    public String getInnerHead() {
        return innerHead;
    }

    public void setInnerHead(String innerHead) {
        this.innerHead = innerHead;
    }

    public String getInnerIdentify() {
        return innerIdentify;
    }

    public void setInnerIdentify(String innerIdentify) {
        this.innerIdentify = innerIdentify;
    }

    public String getInnerMoblie() {
        return innerMoblie;
    }

    public void setInnerMoblie(String innerMoblie) {
        this.innerMoblie = innerMoblie;
    }

    public String getInnerScore() {
        return innerScore;
    }

    public void setInnerScore(String innerScore) {
        this.innerScore = innerScore;
    }

    public String getInnerServe() {
        return innerServe;
    }

    public void setInnerServe(String innerServe) {
        this.innerServe = innerServe;
    }

    public String getInnerTodayServe() {
        return innerTodayServe;
    }

    public void setInnerTodayServe(String innerTodayServe) {
        this.innerTodayServe = innerTodayServe;
    }

    public String getInnHead() {
        return innHead;
    }

    public void setInnHead(String innHead) {
        this.innHead = innHead;
    }

    public String getInnProducts() {
        return innProducts;
    }

    public void setInnProducts(String innProducts) {
        this.innProducts = innProducts;
    }

    public String getInnName() {
        return innName;
    }

    public void setInnName(String innName) {
        this.innName = innName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
