package com.fm.fmlib.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.fm.fmlib.dao.LocalTitle;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LOCAL_TITLE.
*/
public class LocalTitleDao extends AbstractDao<LocalTitle, Void> {

    public static final String TABLENAME = "LOCAL_TITLE";

    /**
     * Properties of entity LocalTitle.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Dest_id = new Property(0, String.class, "dest_id", false, "DEST_ID");
        public final static Property Dest_name = new Property(1, String.class, "dest_name", false, "DEST_NAME");
    };


    public LocalTitleDao(DaoConfig config) {
        super(config);
    }
    
    public LocalTitleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LOCAL_TITLE' (" + //
                "'DEST_ID' TEXT NOT NULL ," + // 0: dest_id
                "'DEST_NAME' TEXT NOT NULL );"); // 1: dest_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LOCAL_TITLE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LocalTitle entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getDest_id());
        stmt.bindString(2, entity.getDest_name());
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public LocalTitle readEntity(Cursor cursor, int offset) {
        LocalTitle entity = new LocalTitle( //
            cursor.getString(offset + 0), // dest_id
            cursor.getString(offset + 1) // dest_name
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LocalTitle entity, int offset) {
        entity.setDest_id(cursor.getString(offset + 0));
        entity.setDest_name(cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(LocalTitle entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(LocalTitle entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
