package com.fm.fmlib.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCAL_TITLE.
 */
public class LocalTitle {

    /** Not-null value. */
    private String dest_id;
    /** Not-null value. */
    private String dest_name;

    public LocalTitle() {
    }

    public LocalTitle(String dest_id, String dest_name) {
        this.dest_id = dest_id;
        this.dest_name = dest_name;
    }

    /** Not-null value. */
    public String getDest_id() {
        return dest_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDest_id(String dest_id) {
        this.dest_id = dest_id;
    }

    /** Not-null value. */
    public String getDest_name() {
        return dest_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDest_name(String dest_name) {
        this.dest_name = dest_name;
    }

}
