package com.fm.fmlib.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCT_BREVIARY.
 */
public class ProductBreviary {

    /** Not-null value. */
    private String product_id;
    private String price;
    private String old_price;
    private String product_name;
    private String quantity;
    private String score;
    private String state;
    private String thumb;
    private String tuan_end_time;

    public ProductBreviary() {
    }

    public ProductBreviary(String product_id, String price, String old_price, String product_name, String quantity, String score, String state, String thumb, String tuan_end_time) {
        this.product_id = product_id;
        this.price = price;
        this.old_price = old_price;
        this.product_name = product_name;
        this.quantity = quantity;
        this.score = score;
        this.state = state;
        this.thumb = thumb;
        this.tuan_end_time = tuan_end_time;
    }

    /** Not-null value. */
    public String getProduct_id() {
        return product_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProduct_id(String product_id) {
        this.product_id = product_id;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getOld_price() {
        return old_price;
    }

    public void setOld_price(String old_price) {
        this.old_price = old_price;
    }

    public String getProduct_name() {
        return product_name;
    }

    public void setProduct_name(String product_name) {
        this.product_name = product_name;
    }

    public String getQuantity() {
        return quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    public String getScore() {
        return score;
    }

    public void setScore(String score) {
        this.score = score;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public String getTuan_end_time() {
        return tuan_end_time;
    }

    public void setTuan_end_time(String tuan_end_time) {
        this.tuan_end_time = tuan_end_time;
    }

}
