package com.fm.fmlib.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCT.
 */
public class Product {

    /** Not-null value. */
    private String product_id;
    private String agent;
    private String bdgps;
    private String bought_count;
    private String category;
    private String category_id;
    private String comments;
    private String content;
    private String lat;
    private String lon;
    private String old_price;
    private String on_shelves;
    private String price;
    private String score;
    private String product_name;
    private String state;
    private String shelf_count;
    private String thumb;
    private String quantity;
    private String tuan_end_time;

    public Product() {
    }

    public Product(String product_id, String agent, String bdgps, String bought_count, String category, String category_id, String comments, String content, String lat, String lon, String old_price, String on_shelves, String price, String score, String product_name, String state, String shelf_count, String thumb, String quantity, String tuan_end_time) {
        this.product_id = product_id;
        this.agent = agent;
        this.bdgps = bdgps;
        this.bought_count = bought_count;
        this.category = category;
        this.category_id = category_id;
        this.comments = comments;
        this.content = content;
        this.lat = lat;
        this.lon = lon;
        this.old_price = old_price;
        this.on_shelves = on_shelves;
        this.price = price;
        this.score = score;
        this.product_name = product_name;
        this.state = state;
        this.shelf_count = shelf_count;
        this.thumb = thumb;
        this.quantity = quantity;
        this.tuan_end_time = tuan_end_time;
    }

    /** Not-null value. */
    public String getProduct_id() {
        return product_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProduct_id(String product_id) {
        this.product_id = product_id;
    }

    public String getAgent() {
        return agent;
    }

    public void setAgent(String agent) {
        this.agent = agent;
    }

    public String getBdgps() {
        return bdgps;
    }

    public void setBdgps(String bdgps) {
        this.bdgps = bdgps;
    }

    public String getBought_count() {
        return bought_count;
    }

    public void setBought_count(String bought_count) {
        this.bought_count = bought_count;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getCategory_id() {
        return category_id;
    }

    public void setCategory_id(String category_id) {
        this.category_id = category_id;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getLon() {
        return lon;
    }

    public void setLon(String lon) {
        this.lon = lon;
    }

    public String getOld_price() {
        return old_price;
    }

    public void setOld_price(String old_price) {
        this.old_price = old_price;
    }

    public String getOn_shelves() {
        return on_shelves;
    }

    public void setOn_shelves(String on_shelves) {
        this.on_shelves = on_shelves;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getScore() {
        return score;
    }

    public void setScore(String score) {
        this.score = score;
    }

    public String getProduct_name() {
        return product_name;
    }

    public void setProduct_name(String product_name) {
        this.product_name = product_name;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getShelf_count() {
        return shelf_count;
    }

    public void setShelf_count(String shelf_count) {
        this.shelf_count = shelf_count;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public String getQuantity() {
        return quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    public String getTuan_end_time() {
        return tuan_end_time;
    }

    public void setTuan_end_time(String tuan_end_time) {
        this.tuan_end_time = tuan_end_time;
    }

}
